# Database connection properties
db.driver=com.mysql.cj.jdbc.Driver
#db.url=jdbc:mysql://10.100.16.212:3306/test
db.url=jdbc:mysql://kioskmysql.raikmitl.com:3306/test
db.user=root
db.password=w5Rh@C$k

#https://kiosk.raikmitl.com website
# https://kioskmysql.raikmitl.com phpMyAdmin